#!/bin/bash

# check user passed in ldif file
if [ $# -ne 2 ]
then
  echo "Missing parameter!
Usage:
    $0 INPUT_LDIF_FILE  OUTPUT_LDIF_FILE"
  exit 1
fi

if ! [ -r $1 ]
then
  echo "$1 is not readable!"
  exit 1
fi

> $2
if [ $? -ne 0 ]
then
  echo "$2 is not writable!"
  exit 1
fi

buffer=""
outfile=""

# Remove old temporary files
rm *.tmp

while read line
do
  # New entry start
  if [[ $line =~ ^dn: ]]
  then
    echo "--Start->$line"
    # Work out which tmp file to put in, based on how many components in DN
    outfile="$(echo $line | awk -F',' '{ print NF }').tmp"
    echo "$buffer
$line" >> $outfile
    # Empty buffer
    buffer=""
  else
    # No designated outfile means lines before or between entries
    if [[ $outfile == "" ]]
    then
      # Store in buffer, part of next entry
      buffer="$buffer
$line"
    else      
      # Newline marks end of current entry
      if [[ $line == "" ]]
      then
        # Set outfile to ""
        outfile=""
      else
        # Part of current entry
        echo $line >> $outfile  
      fi
    fi
  fi
done < $1

for outfile in $(ls *.tmp | sort)
do
  cat $outfile >> $2 
done

echo $buffer >> $2
