#!/bin/bash

# Debug mode
DEBUG=1

# Spawn limit
LIMIT=7
# Wait time
PSWAIT=5

# Variables
N=0
psVars=("A,1" "B,2" "C,3" "D,4" "E,5" "F,6" "G,7" "H,8" "I,9" "J,10" "K,11")

# Make temporary workspace
cd "$(mktemp -d)"

# Make lock file
#: >> lock
echo $LIMIT > lock

psRun () {
    local psVar=$1

    while :
    do
        {
        flock $fd
            N=$(head -1 lock)
            if [ $N -gt 0 ]
            then
                [ $DEBUG -eq 1 ] && echo "PID $BASHPID: Take 1 from N($N)"
                ((N--))
                echo $N > lock
                flock -u $fd
                break
            fi
        } {fd}<lock
        flock -u $fd
        sleep $PSWAIT
    done

    #### Replace this section with your code ###
    echo "PID $BASHPID: running - psVar($psVar)"
    sleep 15
    echo "PID $BASHPID: finished"
    ############################################

    {
    flock $fd
        N=$(head -1 lock)
        [ $DEBUG -eq 1 ] && echo "PID $BASHPID: Give 1 to N($N)"
        ((N++))
        echo $N > lock
    } {fd}<lock

    # Exit child process
    exit 0
}

for psVar in ${psVars[@]}
do
    [ $DEBUG -eq 1 ] && echo "Parent PID $$ $BASHPID: $psVar"
    psRun "$psVar" &
done

until [ $N -eq $LIMIT ]
do
    sleep $((PSWAIT * 2))
    {
    flock $fd
        N=$(head -1 lock)
        [ $DEBUG -eq 1 ] && echo "Parent PID $$ $BASHPID: N($N)"
    } {fd}<lock
    flock -u $fd
done

# Clean up
rm -r $PWD
